### ISSUE TITLE
100% Docker CPU Usage

### ISSUE THREAD

**Issue by xrizonx** [yanickflyer/airlinemanager4bot#2]
Hi,

Thanks a million for this quite easy to get going in docker. Only issue i am seeing my side is that this uses 100% CPU all the time have since set portainer to limit it to 1 CPU Core but even on 48 same issue.

any idea what might be causing this.

This is the log
Eco Campaign is already ActiveNo Need to buy FUEL. Hold is at 12954718LBS
No Need to buy CO2 Quota. Hold is at 10,402,076 Quotas
Exception in thread Thread-3 (check_marketing):
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1080, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/usr/local/lib/python3.13/threading.py", line 1017, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/launch.py", line 19, in check_marketing
    marketing.marketing.eco_campaign()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/src/marketing.py", line 30, in eco_campaign
    get_ecotimer=int(get_ecotimer.split(',')[1].rstrip(')'))
                 ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: "9393);timer('c75939969timer'"
All Aircraft are in the air
Current Account Balance is $32,995,822

**Comment by yanickflyer** [comment]
Hi @xrizonx,

Yeah am not maintaining anymore. I got banned. So they have policies in place against bots and script.. So watch out when you are running this. I'd advise to put sleeps in between request in a randomize way for you not to get caught.

As for the above error, they probably had a recent update on the HTML code and so the marketing renewal might not work anymore.
And I won't be able to debug as; well I got banned 😅

As for the High Usage it is because I use recursive functions and multi-threading to retry some actions.

If you want to stop the behaviour just comment **Line 10** in **main.py** but it will disable marketing campaign feature.
`thread3.start()`
